name: Hello World Repo Dispatch
on:
  #repository_dispatch:
  #  types: example-event
  release:
    types: created
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: |
        echo Greetings from v2 branch!
        echo ${{ github.event.client_payload.foo }}